[amap]
# key = "1234567890abcdef1234567890abcdef"
key = "1688c721afe4285ce95351c925024a11"

[transport]
poi = ["新金桥路1348号", "芒果广场"]
strategy = 0
# strategy 为公交换乘策略，填写对应数字
# 可选值：
# 0：推荐模式，综合权重，同高德APP默认
# 1：最经济模式，票价最低
# 2：最少换乘模式，换乘次数少
# 3：最少步行模式，尽可能减少步行距离
# 4：最舒适模式，尽可能乘坐空调车
# 5：不乘地铁模式，不乘坐地铁路线
# 6（未开发，不要选）：地铁图模式，起终点都是地铁站
# 7：地铁优先模式，步行距离不超过4KM
# 8：时间短模式，方案花费总时间最少
night = 0  # night控制是否考虑夜班车，0不考虑，1考虑
time = "9-00"  # time控制计算导航时间时考虑的时刻，可设为上班时间，格式如9-00，需置于双引号之中
